name: test workflow
on: workflow_dispatch
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4
      - name: run build and test
        uses: addnab/docker-run-action@v3
        with:
          image: gradle:6-jdk11
          options: -v ${{ github.workspace }}:/home/gradle/app
          run: |
            echo "Running Script"
            /home/gradle/app/ci/build-app.sh
            /home/gradle/app/ci/unit-test-app.sh
      - name: run linting
        uses: super-linter/super-linter/slim@v7.0.0
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_ERRORS: true
      - name: build docker
        run: bash ci/build-docker.sh
      - name: push docker
        run: bash ci/push-docker.sh
      - name: Execute component test
        run: bash ci/component-test.sh
      - name: Execute performance test
        run: bash ci/performance-test.sh
