name: test workflow
on: workflow_dispatch
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4
      - name: run build and test
        uses: addnab/docker-run-action@v3
        with: 
          image: gradle:6-jdk11
          options: -v ${{ github.workspace }}:/work
          run: |
            echo "Running Script"
            /work/ci/build-app.sh
            /work/ci/unit-test-app.sh
      - name: run linting
        uses: super-linter/super-linter/slim@v7.0.0
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_ERRORS: true
